### ISSUE TITLE
Training issues

### ISSUE THREAD

**Issue by zzff1121** [thuml/MotionRNN#2]
作者你好，我在运行MNIST数据集时，MSE只在 0 ~ 50000次迭代中逐渐下降（81.4到55.3），后面的 50000 ~ 100000次迭代中不再有明显下降，请问这可能由哪些因素导致的。附图记录的是训练过程中loss值变化。
![iterations_loss](https://user-images.githubusercontent.com/37967997/230262677-1f1460ab-96e6-41f7-b62f-33b4068abd6c.png)

**Comment by wuhaixu2016** [comment]
您好，这个可能是因为mnist数据本身的运动比较简单，没办法体现出motionrnn对于形变等复杂运动的建模能力。
